language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

sudo: false

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

install:
    - composer install

script: vendor/bin/phpunit -c tests/phpunit.xml.dist --coverage-clover=coverage.clover
